name: news_json
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:

#JSON Package
  json_annotation: ^4.3.0
  pretty_dio_logger: ^1.2.0-beta-1



  flutter:
    sdk: flutter
#State Management
  mobx: ^2.0.5
  mobx_codegen: ^2.0.4
  flutter_mobx: ^2.0.2
#Network Management
  dio: ^4.0.4
  http: ^0.13.4
#Other Package
  flutter_dotenv: ^5.0.2
  google_fonts: ^2.1.1
  image: ^3.1.0
  cupertino_icons: ^1.0.2
  
  

dev_dependencies:
#Code Generator
  build_runner: ^2.1.5

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  #DEV-JSON Package
  json_serializable: ^6.0.1

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/images/
