name: news_json
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_mobx: ^2.0.2
  google_fonts: ^2.1.1
  http: ^0.13.4
  image: ^3.1.0
  json_annotation: ^4.3.0
  mobx: ^2.0.5
  mobx_codegen: ^2.0.4
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies:
  build_runner: ^2.1.5

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  #DEV-JSON Package
  json_serializable: ^6.0.1

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/images/
